### ISSUE TITLE
Question: Recipes as nodes or nah?

### ISSUE THREAD

**Issue by simpsus** [simpsus/factoriograph#1]
If they are nodes, it is clear what goes into a recipe and what comes out.
Recipes are not really nodes, so in the "BOM" of factorio there are no recipes.

What do you think?

**Comment by amarvin** [comment]
Materials should be nodes, and it's a good question if BOMs should also be a type of node. I find a graph to be unclear if the BOMs are inverted (i.e. multiple outputs like oil processing, taking liquids out of barellels) or there are alternative recipes (i.e. oil processing). So I think the nature of the Factorio BOM requires BOMs to also be nodes.

**Comment by simpsus** [comment]
I tend to agree. On the other hand ... if we want to create an appealing visual, only the materials should be nodes. 
Suggestion: We do it with nodes and see where we end up
